window.BDX_VENDOR={l:'http://www.biddingx.com?utm_campaign=jiaobiao&%%BDX_EXT%%'};
(function(n,p){function k(a){try{var c="_bdxlog_"+ +new Date+Math.floor(1E5*Math.random()),b=n[c]=new Image;b.onload=b.onerror=function(){n[c]=F};b.src=a}catch(d){try{p.createElement("img").src=a}catch(e){}}}function u(h,c){a.ssl||k(G+h+"&n="+v(c.name)+"&m="+v(c.message)+"&s="+v(c.stack&&String(c.stack).slice(0,200)))}function J(a){var c={quality:"high",align:"middle",menu:"false",wmode:"transparent"},b;for(b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);var d='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" type="application/x-shockwave-flash" ',
e='<embed src="'+c.swf+'" type="application/x-shockwave-flash" ',l='<param name="movie" value="'+c.swf+'">';c.swf=F;for(b in c)c[b]!==F&&(a=b+'="'+c[b]+'" ',0>",width,height,hspace,vspace,align,class,id,name,style,".indexOf(","+b+",")?l+='<param name="'+b+'" value="'+c[b]+'">':d+=a,e+=a);return d+">"+l+e+"></embed></object>"}function A(h){return h.replace(/%%BDX_EXT%%/g,a.bdx_ext).replace(/%%BDX_WIDTH%%/g,a.width).replace(/%%BDX_HEIGHT%%/g,a.height).replace(/%%BDX_EXT_ENC%%/g,v(a.bdx_ext)).replace(/%%BDX_HOST%%/g,
q)}function K(h){return h.replace(/\{\$(\w+)\}/g,function(c,b){return a[b]||""})}function S(h){if("c"==h){var c;(c=a.end)&&k(A(c).replace(/_JS_/g,1));if(c=a.click_track)for(h=c.length;0<h--;)k(A(c[h]).replace(/_JS_/g,1))}}function L(){try{for(var h;!h||n[h]||document.getElementById(h);)a.id=h="BDX"+Math.round((new Date).getTime()*Math.random());var c=a.logo,c=0<=c&&4>c?[1,0,3,2][c]:-1,b=m.hasOwnProperty(M)?m[M]:0;b&&(r=q+(m.hasOwnProperty("v")?m.v:void 0)+"/"+N,b[c]||(c=-1));a.link=m.hasOwnProperty("l")?
m.l:"http://www.biddingx.com";a.about=m.hasOwnProperty("t")?m.t:"Biddingx.com\u63d0\u4f9b\u7684\u5e7f\u544a";var d="CSS1Compat"!==p.compatMode&&p.body?p.body:p.documentElement,e=d&&d.clientHeight||0,l=d&&d.clientWidth||0,s=a.width,g=a.height;0>=s&&(s=-s,a.width=s||l);0>=g&&(a.height=-g||e);var H=a.container&&document.getElementById(a.container),b="",e=["","{padding:0;margin:0;position:relative;width:{$width}px;height:{$height}px;overflow:hidden;}","-clk {z-index:10;position:absolute;top:0;left:0;width:{$width}px;height:{$height}px;display:block;filter:alpha(opacity=0);opacity:0;background:#FFF;}",
"-vp {z-index:1;position:relative;padding:0;margin:0;width:{$width}px;height:{$height}px;}"];-1!=c&&(e.push("-logo {z-index:20;display:block;position:absolute;{$pos};width:"+T+"px;height:"+U+"px;text-indent:90em;overflow:hidden;outline:0;blr:expression(this.onFocus=this.blur());}","-logo:hover {width:"+V+"px;cursor:pointer;}","-logo "+'{background:url("{u}") no-repeat;_background:none;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="{u}");}'.replace(/\{u\}/g,"{$sLogo}"),"-logo:hover "+
'{background:url("{u}") no-repeat;_background:none;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="{u}");}'.replace(/\{u\}/g,"{$bLogo}")),a.sLogo=r+c+"s.png",a.bLogo=r+c+"b.png",a.pos=["left:0;top:0","top:0;right:0","right:0;bottom:0","bottom:0;left:0"][c]);e=e.join("\n."+h);if(H&&document.body){var e=K(e),w=document.createElement("style");w.type="text/css";w.styleSheet?w.styleSheet.cssText+=e:w.innerHTML+=e;document.body.appendChild(w)}else b="<style>"+e+"</style>";var w={html:4,mv:-2,
swf:1,flv:2,img:3,png:3,gif:3,jpg:3,jpeg:3},f=a.type||a.url.split(".").pop().toLowerCase(),I=a.ct||w[f]||0;if(f=a.end)a.end=a.click,a.click=f;n[h]=S;0<I&&(b+='<a class="{$id}-clk" target="_blank" href="{$click}" onclick="try{{$id}(\'c\')}catch(e){}"></a>');-1!=c&&(b+='<a href="{$link}" target="_blank" class="{$id}-logo" title="{$about}">{$about}</a>');a.mark=a.mark||1;-1!=a.mark&&(b+='<img src="'+(q+"/data/v/res/m"+a.mark+".png")+'" style="position:absolute!important;left:0!important;bottom:0!important;top:auto!important;right:auto!important;z-index:2!important;width:auto!important;height:auto!important;"/>');
1>5*Math.random()&&(b+='<div style="position:absolute;top:-1000px;">'+J({swf:"{$base}/ui/fc.swf",width:1,height:1})+"</div>");var c='<div id="{$id}" class="{$id}">'+b,O=a.url,f='<div class="{$id}-vp" id="{$id}VP">';switch(I){case 1:f+=J({swf:O,width:a.width,height:a.height});break;case 2:case -2:f+=J({swf:W,flashvars:"video="+v(O)+"&amp;clickTAG="+v(a.click),scale:"noscale",width:a.width,height:a.height});break;case 3:f+='<img src="{$url}" width="{$width}" height="{$height}" border="0"/>';break;default:a.url=
-1===I?"about:blank":a.url+("#"+a.click),f+='<iframe id="{$id}IF" src="{$url}" width="{$width}" height="{$height}" scrolling="no" border="0" frameborder="0" style="border:none;" marginheight="0" marginwidth="0" allowtransparency="true"></iframe>'}b=c+(f+"</div>")+"</div>";b=A(K(b));H?H.innerHTML+=b:p.write(b);P&&p.close();b=document.getElementById(h);0<l&&b.clientWidth>l&&(b.style.cssText+=";-webkit-transform-origin: left top;-webkit-transform: scale("+l/s+");");if(-1==I)if(b=document.getElementById(h+
"IF")){var Q=A(a.adm);try{d=b.contentDocument,d.write(Q),d.close()}catch(x){try{d=b.contentWindow.document,d.write(Q),d.close()}catch(t){u(49,t)}}}else k(G+"997&n=iframe_not_found&"+R);X(n,document.getElementById(a.id),a.bdx_ext,a.ssl,k)}catch(Y){u(0,Y)}}function X(a,c,b,d,e){function l(a){e((g+b+"&vb="+a).replace(/_JS_/g,1))}var g=(d?"https":"http")+"://ana.masky.biddingx.com/masky/ana/ex/e.gif?",p=10;if(b&&c)var m=setInterval(function(){try{for(var b=c,f=a,d=b.offsetParent,e=0,g=b.clientWidth,x=
0,t=b.clientHeight,n=b.clientWidth*b.clientHeight,y=0,z=0,k=!0,v=1;d;){var q=b.clientWidth,r=b.clientHeight,A=b.offsetTop,s=d.clientWidth,u=d.clientHeight,F=d.scrollTop,y=b.offsetLeft-d.scrollLeft,z=A-F,B=0,C=0,D=0,E=0;y>s?B=s:0<y&&(B=y);z>u?C=u:0<z&&(C=z);y+q>s?D=s:0<y+q&&(D=y+q);z+r>u?E=u:0<z+r&&(E=z+r);if(C>=E||B>=D){k=!1;break}if((E-C)*(D-B)<n/2){k=!1;break}e+=y;0>e?e=0:e<B&&(e=B);g+=y;0>g?g=0:D<g&&(g=D);x+=z;0>x?x=0:x<C&&(x=C);t+=z;0>t?t=0:E<t&&(t=E);if(x>=t||e>=g){k=!1;break}if((t-x)*(g-e)<
n/2){k=!1;break}b=d;d=b.offsetParent;!d&&v&&(f.top!=f?(d=f.frameElement,f=f.parent):(d=f.document.documentElement,--v))}k&&!--p&&(l(1),clearInterval(m))}catch(G){l(9),clearInterval(m)}},200)}var N="t",M="o",T=24,V=130,U=18,W="{$base}/ui/player.swf",F,v=encodeURIComponent,G="http://test.masky.biddingx.com/e.gif?p=",a=n.BDX_INFO,R=+new Date;if(!a)return k(G+"998&n=no_info&"+R),!1;var q="http://stuff.cdn.biddingx.com",r=a.base;r&&(q=r.split("/",3).join("/"));a.base=q;var r=q+"/main/script/resource/"+N+"/",m=n.BDX_VENDOR||
{},P=0;try{var g=a.track;if(g)for("string"==typeof g&&(g=[g]);g.length;)k(A(g.shift()).replace(/_JS_/g,1));else u(2,{name:"no_track_info"})}catch(Z){u("imp_dbg",Z)}p.body?L():(P=1,setTimeout(L,10))})(window,document);
